### ISSUE TITLE
Python3.4 support?

### ISSUE THREAD

**Issue by montanaviking** [vMeijin/pySmithPlot#10]
Hi,
Does your software support Python 3.x? I seem to have errors when I try to use it with Python 3.4.
Thanks,
Phil

**Comment by crazyfermions** [comment]
Check out this pull request: https://github.com/vMeijin/pySmithPlot/pull/11
It worked for me in Py3.5.

**Comment by vMeijin** [comment]
Please check the new release version 0.2.
