### ISSUE TITLE
not working with Python2.7

### ISSUE THREAD

**Issue by rbunger** [vMeijin/pySmithPlot#13]
Hi,

thanks for the update, but it is not working with Python2.7 (tested with Ubuntu and CentOs). The problem is with the arguments of member functions "_moebius_z" and "_moebius_inv_z" where the parameter "normalize" follows "*args" which seems to cause the problem with Python2.7.

Also, if using with Python3, one of the examples is not working due the special character \Omega...

Thanks,

Rainer

**Comment by feph** [comment]
Hi, I forked and fixed this for me, maybe somebody wants to test my solution as well. (see https://github.com/feph/pySmithPlot/commit/765b3e72ab34ad0af21fc4b01f4b88e5c45252c4)

**Comment by rbunger** [comment]
Hi, I have tried it and it works, many thanks! But I wonder about the point that the grid looks different now (much denser and the main grid lines at R=0,1, 0.3, 0.6,... and X=+-0.3j,+-0.6j,... are missing now...

**Comment by brainstorm** [comment]
It solves previous errors such as this one for me:

```
$ python
Python 2.7.14 | packaged by conda-forge | (default, Nov  4 2017, 10:22:41)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import smithplot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.9-x86_64/egg/smithplot/__init__.py", line 5, in <module>
  File "/Users/romanvg/.miniconda/envs/limesdr/lib/python2.7/site-packages/pysmithplot-0.2.0-py2.7.egg/smithplot/smithaxes.py", line 557
    def _moebius_z(self, *args, normalize=None):
                                        ^
SyntaxError: invalid syntax
>>>
```

But it fails in another way:

```
$ python calculateVNA.py r50 plot
Traceback (most recent call last):
  File "calculateVNA.py", line 26, in <module>
    from smithplot.smithaxes import update_scParams
ImportError: cannot import name update_scParams
```

**Comment by vMeijin** [comment]
I am not using python 2.7 anymore and wont support backward compatibility for it.
