### ISSUE TITLE
Package for PyPI

### ISSUE THREAD

**Issue by phaethon** [vMeijin/pySmithPlot#17]
This is by no means critical, but having a PyPI package for pySmithPlot would be convenient.

**Comment by brainstorm** [comment]
https://pypi.python.org/pypi/pysmithplot/0.1.0

**Comment by K1ngjulien** [comment]
Would it be hard to update the package to 0.2.0?  I mean its not hard to install without pip but it would be much more convenient.

**Comment by brainstorm** [comment]
That's very much on @vMeijin 's hands to do/update, +1 :/

**Comment by vMeijin** [comment]
I am not sure who added the package, but it was not me.

**Comment by matsievskiysv** [comment]
Hello! I've published your package under the name [pysmithplot-fork](https://pypi.org/project/pysmithplot-fork/). I hope that you'll publish the official version.
