### ISSUE TITLE
Smith Chart Formatting is messed up in Matplotlib 2.1.2, works in 2.0.2

### ISSUE THREAD

**Issue by chrisgmorton** [vMeijin/pySmithPlot#19]
I believe the Matplotlib team made changes to polar plot which I presume is the culprit.
Best, Chris.

**Comment by chrisgmorton** [comment]
Some exchanges with MPL team on this issue; removing the 'reverse' code does go some way to sorting out the grid line but there are till issues;

https://github.com/matplotlib/matplotlib/issues/10654#issuecomment-370105872

**Comment by vMeijin** [comment]
Thanks for your effort. I will have a look at the issue in the near future, but not before April. I guess I have an idea where the problem comes from.

**Comment by chrisgmorton** [comment]
Great thanks.

**Comment by vMeijin** [comment]
The Issue should be solved. Matplotlib changed something in the 'Arc' class, which broke the grid generation.
