### ISSUE TITLE
Support for data outside of Smith Chart? (active devices)

### ISSUE THREAD

**Issue by thgngu** [vMeijin/pySmithPlot#26]
Hello,

First of all, very nice tool. Thanks a lot for your work.

Any plans or thoughts on supporting for data that go outside of the unit circle?

Thanks

**Comment by ChrisHoyer** [comment]
Hi,

just set the  clip_on flag to false, like:

`plt.plot(Data, datatype=SmithAxes.S_PARAMETER,  clip_on=False) `
