### ISSUE TITLE
Convert purely real input to complex

### ISSUE THREAD

**Issue by SjoerdOptLand** [vMeijin/pySmithPlot#3]
When plotting a simple point, I noticed that passing a purely real number bugs. The first point ends up at 2.5 (OK), the second point at 2.5j (NOK). MWE:
```
import sys
sys.path.append("pySmithPlot")

from matplotlib import pyplot
import smithplot

axes = pyplot.subplot(1, 1, 1, projection='smith', axes_norm=1.0)
pyplot.plot(2.5+0j, markevery=5, label='2.5+0j')
pyplot.plot(2.5, markevery=5, label='2.5')
pyplot.legend()
pyplot.show()
```
![purely_real_argument](https://f.cloud.github.com/assets/1442504/2041414/e4f51316-89c4-11e3-93ea-74af0d6cc4e6.png)

**Comment by vMeijin** [comment]
Please check the new release version 0.2.
