### ISSUE TITLE
Intall pysmithplot

### ISSUE THREAD

**Issue by anthonnyt** [vMeijin/pySmithPlot#9]
I download pySmithPlot-master and I used pip install pysmithplot and that didn't install pysmithplot... I have matplotlib >1.2 and the numpy lib... What is the problem? Help please

**Comment by carloskmilo** [comment]
What version of python do you have?

**Comment by anthonnyt** [comment]
I have version 2.7.9

**Comment by DrRogla** [comment]
I have version 3.5 and didn't work through pip for me either.

I downloaded the project and ran setup "python setup.py install" and it works perfectly.

**Comment by vMeijin** [comment]
I dont know who puts the packages into the pip repository but I am not responsible for this. If you want to install the package, you have to download the current version and run the following command inside the base directory: 
python3 ./setup.py install

**Comment by ingelectronicadj** [comment]
Hi friend, thanks for the input
¿license? Add the GNU license
I want to implement it and share it
